[package]
name = "alyx-host"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
alyx-plan = { path = "../alyx-plan" }
alyx-web = { path = "../alyx-web" }
alyx-runtime = { path = "../alyx-runtime" }
alyx-executor = { path = "../alyx-executor" }

[dev-dependencies]
alyx-ir = { path = "../alyx-ir" }
